### ISSUE TITLE
Timeouts not working reliably 

### ISSUE THREAD

**Issue by leftieFriele** [podium-lib/client#408]
Thee effect of setting a timeout in `layout.client.register` is unclear and does not seem to work predictably. 

A timeout of 1 ms only causes a `BodyTimeoutError` on some requests. 

Other times the request goes through.
If we "patch" the podium HTTP client in [http.js](https://github.com/podium-lib/client/blob/main/lib/http.js#L21) with an `AbortSignal` with the corresponding `bodyTimeout` the requests consistently fail as we expect:

```js
async request(url, options) {
    const { statusCode, headers, body } = await request(
        new URL(url),
        {...options, signal: url.includes('manifest') ? undefined : AbortSignal.timeout(options.bodyTimeout)},
    );
    return { statusCode, headers, body };
}
```

Possibly related issue:
https://github.com/nodejs/undici/issues/3297

**Comment by digitalsadhu** [comment]
Fixed in https://github.com/podium-lib/client/pull/409
